networks:
 students_network:
 driver: bridge
services:

  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env
    networks:
      - students_network
    volumes:
      - postgres:/var/lib/postgresql/data
    

  node_app:
    container_name: node_app
    build: . 
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - students_network
volumes:
  postgres:  